#Codes and static resources are copied. Rebuild is needed
#for any change.
version: "3.9"

services:
  db:
    image: mysql:8
    container_name: shopping-db
    restart: on-failure
    command: --authentication_policy=mysql_native_password
    # Creates folders if not existing on compose up.
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file:
      - ./.env.deploy
    cap_add:
      # CAP_SYS_NICE to enable MySQL to handle thread
      # priorities, no more "mbind: Operation not permitted"
      - SYS_NICE
  rabbit:
    image: rabbitmq:3.10
    container_name: shopping-rabbit
    restart: on-failure
    env_file:
      - ./.env.deploy
  redis:
    image: redis:7.0
    container_name: shopping-redis
    restart: on-failure
    env_file:
      - ./.env.deploy
  web:
    image: ypeng90/shopping:web
    container_name: shopping-web
    restart: on-failure
    command: ["sh", "-c", "python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - static:/home/app/staticfiles
    env_file:
      - ./.env.deploy
    depends_on:
      - db
    networks:
      - default
      - scraper
  worker:
    image: ypeng90/shopping:web
    container_name: shopping-worker
    restart: on-failure
    command: ["sh", "./wait-for", "web:8000", "--", "sh", "-c", "celery -A shopping worker --concurrency=4 -l info -O fair"]
    env_file:
      - ./.env.deploy
    depends_on:
      - rabbit
      - redis
      - web
    networks:
      - default
      - scraper
  nginx:
    image: ypeng90/shopping:nginx
    container_name: shopping-nginx
    restart: on-failure
    volumes:
      - static:/home/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static:

networks:
  default:
    name: shopping
  scraper:
    name: scraper