#Codes and static resources are copied. Rebuild is needed
#for any change.
version: "3.9"

services:
  web:
    build:
      context: ./scraper
      dockerfile: Dockerfile.prod
    image: scraper-web
    container_name: scraper-web
    restart: on-failure
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.prod

networks:
  default:
    name: scraper